/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Uts;

/**
 *
 * @author ACER
 */
public class UtsEnkripsi extends javax.swing.JFrame {

    /**
     * Creates new form UtsEnkripsi
     */
    char[] subtitusi ={'0','1','2','3','4','5','6','7','8','9',' ','.',',','@',+
                 'Z','a','Y','b','X','c','W','d','V','e','U','f','T','g','S','h','R','i','Q','j','P','k','O','l','N','m','M',+
                'n','L','o','K','p','J','q','I','r','H','s','G','t','F','u','E','v','D','w','C','x','B','y','A','z'};
    String result = "";
    int standarisasi = 3;
    char c = 0;
    String temp = "";
    StringBuilder enkripsi, dekripsi;
    
    public UtsEnkripsi() {
        initComponents();
        this.setTitle("Enkripsi MYMR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taInput = new javax.swing.JTextArea();
        cbType = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        txtHasil = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taInput.setColumns(20);
        taInput.setRows(5);
        jScrollPane1.setViewportView(taInput);

        cbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enkripsi", "Dekripsi" }));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Hasil :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHasil)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if(cbType.getSelectedItem().equals("Enkripsi")){
            txtHasil.setText("");
            enkripsi();
        }else {
            txtHasil.setText("");
            dekripsi();
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void enkripsi(){
        temp = "";
        result = "";
        temp = taInput.getText();
        enkripsi = new StringBuilder();
        for (int k = 0; k <temp.length(); k++){
         c = temp.charAt(k);
//       System.out.println(c);
         for(int i=0; i<=65; i++){
                if(c == subtitusi[i]){
                i = i+(standarisasi);
                  if(i>=66){
                      i = i-66;
                   }
                   c = subtitusi[i];
                   result = result + c;
                }
            }
        }
        result = "my"+result+"mr";
        enkripsi.append(result);
        enkripsi = enkripsi.reverse();
        txtHasil.setText(enkripsi.toString());
        enkripsi.delete(0, enkripsi.length());
    }
    
    private void dekripsi(){
        temp = "";
        result = "";
        temp = taInput.getText();
        dekripsi = new StringBuilder();
        dekripsi.append(temp);
        dekripsi = dekripsi.reverse();
        for (int k = 2; k <dekripsi.length()-2; k++)
        {
            c = dekripsi.charAt(k);
//            System.out.println(c);
            for(int i=0; i<=65; i++){
                if(c == subtitusi[i]){
                    i = i-(standarisasi);
                    if(i<=-1){
                       i = i+66;
                    }
                    c = subtitusi[i];
                    result = result + c;
                }
            }
        }
        txtHasil.setText(result);
        dekripsi.delete(0, dekripsi.length());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UtsEnkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UtsEnkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UtsEnkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UtsEnkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UtsEnkripsi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taInput;
    private javax.swing.JTextField txtHasil;
    // End of variables declaration//GEN-END:variables
}
