package Pbo_Rental;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormRental extends javax.swing.JFrame {
    
    public void tampilkanData() {
        String[] kolom = {"ID Transaksi", "Pelanggan", "Jenis Kamar", "Tanggal CheckIn", "Lama Sewa", "Total", "Status"};
        ArrayList<Transaksi> list = new Transaksi().getAll();
        Object rowData[] = new Object[7];
        
        tblTransaksi.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for (int i = 0; i < list.size(); i++) {
            rowData[0] = list.get(i).getIdTransaksi();
            rowData[1] = list.get(i).getNama();
            rowData[2] = list.get(i).getJenis();
            rowData[3] = list.get(i).getTglCheckin();
            rowData[4] = list.get(i).getLamaSewa();
            rowData[5] = list.get(i).getTotalHarga();
            rowData[6] = list.get(i).getStatus();
            
            ((DefaultTableModel)tblTransaksi.getModel()).addRow(rowData);
        }
    }
    
    public FormRental() {
        initComponents();
        tampilkanData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtNotelp = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        txtLamasewa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        cmbKamar = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtNik = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 204));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel3.setText("Alamat");

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel4.setText("No. Telepon");

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel1.setText("Jenis Kamar");

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel6.setText("Lama Sewa");

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel7.setText("Tanggal Check In");

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Pelanggan", "Jenis Kamar", "Tanggal CheckIn", "Lama Sewa", "Total", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblTransaksi);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        cmbKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "Deluxe", "Premium" }));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setText("NIK");

        jLabel9.setFont(new java.awt.Font("Mistral", 0, 36)); // NOI18N
        jLabel9.setText("HOTEL TRETES RAYA");

        jLabel10.setText("*Format YYYY-MM-DD");

        jLabel11.setText("Jl. Raya Tretes Prigen, Pasuruan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLamasewa, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNotelp)
                                        .addComponent(cmbKamar, 0, 270, Short.MAX_VALUE))
                                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 18, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNik, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNotelp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel10)
                                .addGap(17, 17, 17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLamasewa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String k = cmbKamar.getSelectedItem().toString();
        if (k.equalsIgnoreCase("Reguler")) {
            RegulerBed reguler = new RegulerBed();
            Kamar kmr = reguler;
            User user = new User();
            user.setNik(Integer.parseInt(txtNik.getText()));
            user.setNama(txtNama.getText());
            user.setAlamat(txtAlamat.getText());
            user.setNo_telp(txtNotelp.getText());
            if (user.getByNik(user.getNik()).getNik() == 0) {
                user.save();
                Transaksi transaksi = new Transaksi();
                transaksi.setIdKamar(111);
                transaksi.setTglCheckin(txtTanggal.getText());
                transaksi.setStatus("Pembayaran");
                transaksi.setNik(Integer.parseInt(txtNik.getText()));
                transaksi.setHarga(kmr.getHarga());
                transaksi.setLamaSewa(Integer.parseInt(txtLamasewa.getText()));
                transaksi.setTotalHarga();
                transaksi.save();
                JOptionPane.showMessageDialog(rootPane, "Data Telah Masuk");
                tampilkanData();
            }
            else {
                int konfirmasi = JOptionPane.showConfirmDialog(rootPane, "Data anda sudah terdaftar, Apakah ingin mengedit data yang sudah ada?");
                switch(konfirmasi){
                    case JOptionPane.YES_OPTION:
                        user.update();
                        Transaksi transaksi = new Transaksi();
                        transaksi.setIdKamar(111);
                        transaksi.setTglCheckin(txtTanggal.getText());
                        transaksi.setStatus("Pembayaran");
                        transaksi.setNik(Integer.parseInt(txtNik.getText()));
                        transaksi.setHarga(kmr.getHarga());
                        transaksi.setLamaSewa(Integer.parseInt(txtLamasewa.getText()));
                        transaksi.setTotalHarga();
                        transaksi.update();
                        JOptionPane.showMessageDialog(rootPane, "Data Telah Diedit");
                        tampilkanData();
                        break;
                    case JOptionPane.NO_OPTION:
                        break;
                }
            }
        }
        else if (k.equalsIgnoreCase("Deluxe")) {
            DeluxeBed deluxe = new DeluxeBed();
            Kamar kmr = deluxe;
            User user = new User();
            user.setNik(Integer.parseInt(txtNik.getText()));
            user.setNama(txtNama.getText());
            user.setAlamat(txtAlamat.getText());
            user.setNo_telp(txtNotelp.getText());
            if (user.getByNik(user.getNik()).getNik() == 0) {
                user.save();
                Transaksi transaksi = new Transaksi();
                transaksi.setIdKamar(222);
                transaksi.setTglCheckin(txtTanggal.getText());
                transaksi.setStatus("Pembayaran");
                transaksi.setNik(Integer.parseInt(txtNik.getText()));
                transaksi.setHarga(kmr.getHarga());
                transaksi.setLamaSewa(Integer.parseInt(txtLamasewa.getText()));
                transaksi.setTotalHarga();
                transaksi.save();
                JOptionPane.showMessageDialog(rootPane, "Data Telah Masuk");
                tampilkanData();
            }
            else {
                int konfirmasi = JOptionPane.showConfirmDialog(rootPane, "Data anda sudah terdaftar, Apakah ingin mengedit data yang sudah ada?");
                switch(konfirmasi){
                    case JOptionPane.YES_OPTION:
                        user.update();
                        Transaksi transaksi = new Transaksi();
                        transaksi.setIdKamar(222);
                        transaksi.setTglCheckin(txtTanggal.getText());
                        transaksi.setStatus("Pembayaran");
                        transaksi.setNik(Integer.parseInt(txtNik.getText()));
                        transaksi.setHarga(kmr.getHarga());
                        transaksi.setLamaSewa(Integer.parseInt(txtLamasewa.getText()));
                        transaksi.setTotalHarga();
                        transaksi.update();
                        JOptionPane.showMessageDialog(rootPane, "Data Telah Diedit");
                        tampilkanData();
                        break;
                    case JOptionPane.NO_OPTION:
                        break;
                }
            }
        }
        else if (k.equalsIgnoreCase("Premium")) {
            PremiumBed premium = new PremiumBed();
            Kamar kmr = premium;
            User user = new User();
            user.setNik(Integer.parseInt(txtNik.getText()));
            user.setNama(txtNama.getText());
            user.setAlamat(txtAlamat.getText());
            user.setNo_telp(txtNotelp.getText());
            if (user.getByNik(user.getNik()).getNik() == 0) {
                user.save();
                Transaksi transaksi = new Transaksi();
                transaksi.setIdKamar(333);
                transaksi.setTglCheckin(txtTanggal.getText());
                transaksi.setStatus("Pembayaran");
                transaksi.setNik(Integer.parseInt(txtNik.getText()));
                transaksi.setHarga(kmr.getHarga());
                transaksi.setLamaSewa(Integer.parseInt(txtLamasewa.getText()));
                transaksi.setTotalHarga();
                transaksi.save();
                JOptionPane.showMessageDialog(rootPane, "Data Telah Masuk");
                tampilkanData();
            }
            else {
                int konfirmasi = JOptionPane.showConfirmDialog(rootPane, "Data anda sudah terdaftar, Apakah ingin mengedit data yang sudah ada?");
                switch(konfirmasi){
                    case JOptionPane.YES_OPTION:
                        user.update();
                        Transaksi transaksi = new Transaksi();
                        transaksi.setIdKamar(333);
                        transaksi.setTglCheckin(txtTanggal.getText());
                        transaksi.setStatus("Pembayaran");
                        transaksi.setNik(Integer.parseInt(txtNik.getText()));
                        transaksi.setHarga(kmr.getHarga());
                        transaksi.setLamaSewa(Integer.parseInt(txtLamasewa.getText()));
                        transaksi.setTotalHarga();
                        transaksi.update();
                        JOptionPane.showMessageDialog(rootPane, "Data Telah Diedit");
                        tampilkanData();
                        break;
                    case JOptionPane.NO_OPTION:
                        break;
                }
            }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        txtNik.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        txtNotelp.setText("");
        txtTanggal.setText("");
        txtLamasewa.setText("");
        txtSearch.setText("");
        tampilkanData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        String[] kolom = {"ID Transaksi", "Pelanggan", "Jenis Kamar", "Tanggal CheckIn", "Lama Sewa", "Total", "Status"};
        ArrayList<Transaksi> list = new Transaksi().search(Integer.parseInt(txtSearch.getText()));
        Object rowData[] = new Object[7];
        
        tblTransaksi.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for (int i = 0; i < list.size(); i++) {
            rowData[0] = list.get(i).getIdTransaksi();
            rowData[1] = list.get(i).getNama();
            rowData[2] = list.get(i).getJenis();
            rowData[3] = list.get(i).getTglCheckin();
            rowData[4] = list.get(i).getLamaSewa();
            rowData[5] = list.get(i).getTotalHarga();
            rowData[6] = list.get(i).getStatus();
            
            ((DefaultTableModel)tblTransaksi.getModel()).addRow(rowData);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        new FormBayar().setVisible(true);
    }//GEN-LAST:event_btnBayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbKamar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtLamasewa;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNik;
    private javax.swing.JTextField txtNotelp;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
